/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 16:23:18 GMT 2018
 */

package diamond.bind.state;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import diamond.appstate.ApplicationState;
import diamond.bind.state.PaintBoundStateFactory;
import diamond.paint.EditMode;
import java.awt.Component;
import java.awt.Panel;
import javax.swing.Box;
import javax.swing.JInternalFrame;
import javax.swing.JRadioButton;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JToolBar;
import javax.swing.JViewport;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PaintBoundStateFactory_ESTest extends PaintBoundStateFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      // Undeclared exception!
      try { 
        paintBoundStateFactory0.create((Component) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("diamond.bind.state.PaintBoundStateFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      Panel panel0 = new Panel();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(panel0, "AddVertex");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      Panel panel0 = new Panel();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(panel0, "Cut_and_Paste");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JInternalFrame jInternalFrame0 = new JInternalFrame();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jInternalFrame0, "SelectLine");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create((Component) null, "Copy_and_Paste");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JViewport jViewport0 = new JViewport();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jViewport0, "EditContour");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JInternalFrame jInternalFrame0 = new JInternalFrame();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jInternalFrame0, "ChangeLineType");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JScrollPane jScrollPane0 = new JScrollPane();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jScrollPane0, "DeleteVertex");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JToolBar.Separator jToolBar_Separator0 = new JToolBar.Separator();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jToolBar_Separator0, "DeleteLine");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      Component component0 = Box.createGlue();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(component0, "selectAll");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JToolBar.Separator jToolBar_Separator0 = new JToolBar.Separator();
      // Undeclared exception!
      try { 
        paintBoundStateFactory0.create(jToolBar_Separator0, "83");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Wrong ID for creating state
         //
         verifyException("diamond.bind.state.PaintBoundStateFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JRadioButtonMenuItem jRadioButtonMenuItem0 = new JRadioButtonMenuItem("Bisector", false);
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jRadioButtonMenuItem0, "ByValue");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create((Component) null, "Symmetric");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JRadioButtonMenuItem jRadioButtonMenuItem0 = new JRadioButtonMenuItem("Bisector", false);
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jRadioButtonMenuItem0, "Bisector");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JSplitPane jSplitPane0 = new JSplitPane(0, (Component) null, (Component) null);
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jSplitPane0, "VerticalLine");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JRadioButton jRadioButton0 = new JRadioButton();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jRadioButton0, "OnV");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      Panel panel0 = new Panel();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(panel0, "TriangleSplit");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create((Component) null, "PBisec");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create((Component) null, "DirectV");
      assertNotNull(applicationState0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PaintBoundStateFactory paintBoundStateFactory0 = new PaintBoundStateFactory();
      JScrollPane jScrollPane0 = new JScrollPane();
      ApplicationState<EditMode> applicationState0 = paintBoundStateFactory0.create(jScrollPane0, "Mirror");
      assertNotNull(applicationState0);
  }
}
