/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Dec 04 16:57:24 GMT 2018
 */

package diamond.view.main;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class UIPanel_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "diamond.view.main.UIPanel"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "MS932"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\long_\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "JP"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\long_\\git\\DIAMOND"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\long_"); 
    java.lang.System.setProperty("user.language", "ja"); 
    java.lang.System.setProperty("user.name", "long_"); 
    java.lang.System.setProperty("user.timezone", ""); 
    java.lang.System.setProperty("sun.java.launcher", "SUN_STANDARD"); 
    java.lang.System.setProperty("user.variant", ""); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(UIPanel_ESTest_scaffolding.class.getClassLoader() ,
      "diamond.paint.creasepattern.Painter",
      "diamond.resource.ResourceHolder",
      "diamond.paint.segment.SelectingSecondVertexForSegment",
      "diamond.doc.exporter.ExporterDXF",
      "diamond.view.main.UIPanel$2",
      "diamond.view.main.UIPanel$3",
      "diamond.fold.TriangleVertex",
      "diamond.file.FileVersionError",
      "diamond.view.main.UIPanel$4",
      "diamond.resource.Constants$EditMode",
      "diamond.view.main.menubar.edit.UnselectAll",
      "diamond.doc.Doc",
      "diamond.view.main.HintLabel",
      "diamond.resource.ResourceKey",
      "diamond.view.main.UIPanel$1",
      "diamond.paint.creasepattern.VerticesManager$AreaPosition",
      "diamond.paint.segment.TwoPointSegmentAction",
      "diamond.Version",
      "diamond.viewsetting.main.uipanel.ChangeOnPaintInputButtonSelected",
      "diamond.paint.creasepattern.VerticesManager",
      "diamond.fold.FoldedModelInfo",
      "diamond.view.main.menubar.file.Save",
      "diamond.paint.core.PickingLine",
      "diamond.doc.DocHolder",
      "diamond.paint.vertical.SelectingLineForVertical",
      "diamond.doc.UndoInfo",
      "diamond.viewsetting.main.ChangeHint",
      "diamond.appstate.GroupMember",
      "diamond.geom.Line",
      "diamond.view.main.menubar.MenuEdit",
      "diamond.doc.loader.LoaderCP",
      "diamond.paint.symmetric.SelectingVertexForSymmetric",
      "diamond.appstate.StateManagerInterface",
      "diamond.file.FileFilterEx",
      "diamond.file.SavingAction",
      "diamond.value.OriLine",
      "diamond.paint.core.GraphicMouseAction",
      "diamond.doc.LoadingDoc",
      "diamond.paint.pbisec.TwoPointBisectorAction",
      "diamond.viewsetting.main.uipanel.FromLineTypeItemListener",
      "diamond.doc.exporter.ExporterSVG",
      "diamond.doc.UndoManager",
      "diamond.doc.loader.LoaderXML",
      "diamond.paint.byvalue.ValueDB",
      "diamond.viewsetting.ChangeViewSetting",
      "diamond.paint.deletevertex.DeletingVertex",
      "diamond.view.main.UIPanel",
      "diamond.fold.TriangleFace",
      "diamond.paint.triangle.TriangleSplitAction",
      "diamond.paint.core.ActionState",
      "diamond.paint.core.AbstractActionState",
      "diamond.viewsetting.model.ModelFrameSettingDB",
      "diamond.resource.WarningStringResource_en",
      "diamond.file.ImageResourceLoader",
      "diamond.paint.deleteline.DeleteLineAction",
      "diamond.file.FilterDB",
      "diamond.viewsetting.estimation.RenderFrameSettingDB",
      "diamond.view.estimation.FoldedModelScreen",
      "diamond.doc.exporter.ExporterXML",
      "diamond.viewsetting.main.MainFrameSettingDB",
      "diamond.viewsetting.ViewScreenUpdater",
      "diamond.fold.OrigamiModel",
      "diamond.view.main.menubar.edit.RepeatCopy",
      "diamond.value.OriLine$Type",
      "diamond.file.LoadingAction",
      "diamond.viewsetting.main.ScreenUpdater",
      "diamond.paint.byvalue.AbstractValueInputListener",
      "diamond.view.main.MainFrame",
      "diamond.viewsetting.main.uipanel.ChangeOnSelectButtonSelected",
      "diamond.view.main.menubar.file.Property",
      "diamond.paint.deletevertex.DeleteVertexAction",
      "diamond.paint.GraphicMouseActionInterface",
      "diamond.paint.EditMode",
      "diamond.view.main.menubar.help.About",
      "diamond.paint.pbisec.SelectingFirstVertexForBisector",
      "diamond.bind.ButtonFactory",
      "diamond.bind.state.LocalPaintBoundStateFactory",
      "diamond.paint.line.TwoPointLineAction",
      "diamond.paint.deleteline.DeletingLine",
      "diamond.view.main.menubar.file.SaveAs",
      "diamond.doc.loader.Loader",
      "diamond.resource.Constants$ModelDispMode",
      "diamond.bind.state.ErrorListener",
      "diamond.paint.core.PaintContext",
      "diamond.paint.pbisec.SelectingSecondVertexForBisector",
      "diamond.doc.exporter.ExporterPNG",
      "diamond.bind.state.action.StateActionPerformer",
      "diamond.paint.selectline.SelectLineAction",
      "diamond.paint.byvalue.LengthMeasuringAction",
      "diamond.paint.geometry.NearestPoint",
      "diamond.doc.loader.LoaderDXF",
      "diamond.appstate.ApplicationState",
      "diamond.viewsetting.main.uipanel.UIPanelSettingDB",
      "diamond.bind.state.action.PaintActionSetter",
      "diamond.paint.creasepattern.tool.PainterCommandFailedException",
      "diamond.doc.exporter.cp.DataSet",
      "diamond.bind.binder.ApplicationStateButtonBinder",
      "diamond.paint.mirror.MirrorCopyAction",
      "diamond.paint.segment.SelectingFirstVertexForSegment",
      "diamond.view.main.menubar.MenuFile",
      "diamond.paint.byvalue.LineByValueAction",
      "diamond.paint.bisector.SelectingVertexForBisector",
      "diamond.bind.PaintActionButtonFactory",
      "diamond.viewsetting.ViewSettingDataBase",
      "diamond.paint.core.PaintConfig",
      "diamond.paint.geometry.NearestVertexFinder",
      "diamond.paint.util.LineTypeSetter",
      "diamond.resource.Constants",
      "diamond.view.model.ModelViewScreen",
      "diamond.resource.Constants$LineInputMode",
      "diamond.paint.geometry.GeometricOperation",
      "diamond.viewsetting.main.MainScreenSettingDB",
      "diamond.view.main.menubar.file.Exit",
      "diamond.paint.creasepattern.tool.TypeForChange",
      "diamond.viewsetting.ViewChangeListener",
      "diamond.resource.ExplanationStringResource_en",
      "diamond.paint.byvalue.SelectingVertexForAngle",
      "diamond.viewsetting.main.uipanel.ChangeOnAlterTypeButtonSelected",
      "diamond.appstate.StateManager",
      "diamond.paint.byvalue.SelectingVertexToDrawLine",
      "diamond.paint.vertical.VerticalLineAction",
      "diamond.appstate.InputCommandStatePopper",
      "diamond.doc.exporter.ExporterOBJ",
      "diamond.paint.creasepattern.LineManager",
      "diamond.paint.creasepattern.tool.LineSelectionModifier",
      "diamond.paint.bisector.AngleBisectorAction",
      "diamond.geom.Ray",
      "diamond.paint.triangle.SelectingVertexForTriangleSplit",
      "diamond.mouse.MouseUtility",
      "diamond.doc.exporter.cp.OriLineProxy",
      "diamond.view.estimation.EstimationResultUI",
      "diamond.paint.linetype.ChangeLineTypeAction",
      "diamond.paint.byvalue.AngleMeasuringAction",
      "diamond.fold.OriFace",
      "diamond.bind.binder.AbstractButtonBinder",
      "diamond.viewsetting.main.uipanel.ChangeOnOtherCommandButtonSelected",
      "diamond.bind.state.PaintBoundStateFactory",
      "diamond.view.main.PainterScreen",
      "diamond.geom.GeomUtil",
      "diamond.view.main.menubar.file.New",
      "diamond.value.OriPoint",
      "diamond.view.main.menubar.file.Open",
      "diamond.paint.byvalue.SelectingVertexForLength",
      "diamond.paint.ScreenUpdaterInterface",
      "diamond.paint.core.PickingVertex",
      "diamond.paint.creasepattern.CreasePattern",
      "diamond.paint.bisector.SelectingLineForBisector",
      "diamond.geom.Segment",
      "diamond.fold.OriHalfedge",
      "diamond.bind.binder.BinderInterface",
      "diamond.appstate.StatePusher",
      "diamond.bind.binder.ViewChangeBinder",
      "diamond.paint.creasepattern.CreasePattern$CreasePatternIterator",
      "diamond.view.estimation.EstimationResultFrame",
      "diamond.resource.LabelStringResource_en",
      "diamond.paint.mirror.SelectingLineForMirror",
      "diamond.paint.symmetric.SymmetricalLineAction",
      "diamond.paint.linetype.SelectingLineForLineType",
      "diamond.doc.loader.LoaderPDF",
      "diamond.paint.line.SelectingSecondVertexForLine",
      "diamond.paint.selectline.SelectingLine",
      "diamond.paint.line.SelectingFirstVertexForLine",
      "diamond.view.main.menubar.edit.CircleCopy",
      "diamond.viewsetting.main.uipanel.ToLineTypeItemListener",
      "diamond.viewsetting.main.ScreenUpdater$KeyListener",
      "diamond.fold.BoundBox",
      "diamond.view.main.menubar.MenuHelp",
      "diamond.doc.exporter.ExporterCP",
      "diamond.paint.addvertex.AddVertexAction",
      "diamond.paint.core.RectangularSelectableAction",
      "diamond.view.model.ModelViewFrame",
      "diamond.paint.addvertex.AddingVertex",
      "diamond.viewsetting.main.uipanel.ChangeOnByValueButtonSelected",
      "diamond.doc.exporter.Exporter",
      "diamond.bind.state.PaintBoundState",
      "diamond.doc.SavingDoc",
      "diamond.paint.vertical.SelectingVertexForVertical",
      "diamond.paint.byvalue.AngleValueInputListener",
      "diamond.view.main.menubar.edit.Undo",
      "diamond.paint.byvalue.LengthValueInputListener",
      "diamond.view.main.menubar.MenuBar"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.awt.event.HierarchyBoundsListener", false, UIPanel_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(UIPanel_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "diamond.view.main.UIPanel",
      "diamond.view.main.UIPanel$1",
      "diamond.view.main.UIPanel$2",
      "diamond.view.main.UIPanel$3",
      "diamond.view.main.UIPanel$4",
      "diamond.viewsetting.ViewSettingDataBase",
      "diamond.viewsetting.main.MainScreenSettingDB",
      "diamond.viewsetting.main.uipanel.UIPanelSettingDB",
      "diamond.paint.creasepattern.tool.TypeForChange",
      "diamond.resource.ResourceKey",
      "diamond.resource.ExplanationStringResource_en",
      "diamond.Version",
      "diamond.resource.LabelStringResource_en",
      "diamond.resource.WarningStringResource_en",
      "diamond.resource.ResourceHolder",
      "diamond.paint.byvalue.ValueDB",
      "diamond.paint.EditMode",
      "diamond.doc.Doc",
      "diamond.doc.UndoManager",
      "diamond.paint.creasepattern.CreasePattern",
      "diamond.paint.creasepattern.LineManager",
      "diamond.paint.creasepattern.VerticesManager",
      "diamond.value.OriLine",
      "diamond.value.OriLine$Type",
      "diamond.value.OriPoint",
      "diamond.paint.creasepattern.VerticesManager$AreaPosition",
      "diamond.fold.OrigamiModel",
      "diamond.fold.FoldedModelInfo",
      "diamond.fold.BoundBox",
      "diamond.doc.DocHolder",
      "diamond.viewsetting.main.ScreenUpdater",
      "diamond.resource.Constants$ModelDispMode",
      "diamond.paint.core.GraphicMouseAction",
      "diamond.paint.segment.TwoPointSegmentAction",
      "diamond.paint.core.AbstractActionState",
      "diamond.paint.core.PickingVertex",
      "diamond.paint.segment.SelectingFirstVertexForSegment",
      "diamond.paint.core.PaintConfig",
      "diamond.view.main.MainFrame",
      "diamond.viewsetting.estimation.RenderFrameSettingDB",
      "diamond.viewsetting.model.ModelFrameSettingDB",
      "diamond.view.main.PainterScreen",
      "diamond.paint.core.PaintContext",
      "diamond.bind.binder.AbstractButtonBinder",
      "diamond.bind.binder.ViewChangeBinder",
      "diamond.bind.PaintActionButtonFactory",
      "diamond.bind.state.PaintBoundStateFactory",
      "diamond.bind.state.LocalPaintBoundStateFactory",
      "diamond.paint.addvertex.AddVertexAction",
      "diamond.paint.addvertex.AddingVertex",
      "diamond.viewsetting.ViewChangeListener",
      "diamond.viewsetting.main.uipanel.ChangeOnOtherCommandButtonSelected",
      "diamond.appstate.ApplicationState",
      "diamond.bind.state.PaintBoundState",
      "diamond.appstate.StatePusher",
      "diamond.bind.state.action.PaintActionSetter",
      "diamond.viewsetting.main.ChangeHint",
      "diamond.viewsetting.main.MainFrameSettingDB",
      "diamond.bind.binder.ApplicationStateButtonBinder",
      "diamond.viewsetting.main.ScreenUpdater$KeyListener",
      "diamond.bind.state.action.StateActionPerformer",
      "diamond.paint.core.RectangularSelectableAction",
      "diamond.paint.deleteline.DeleteLineAction",
      "diamond.paint.core.PickingLine",
      "diamond.paint.deleteline.DeletingLine",
      "diamond.paint.deletevertex.DeleteVertexAction",
      "diamond.paint.deletevertex.DeletingVertex",
      "diamond.viewsetting.main.uipanel.ChangeOnPaintInputButtonSelected",
      "diamond.paint.linetype.ChangeLineTypeAction",
      "diamond.paint.linetype.SelectingLineForLineType",
      "diamond.viewsetting.main.uipanel.ChangeOnAlterTypeButtonSelected",
      "diamond.paint.selectline.SelectLineAction",
      "diamond.paint.selectline.SelectingLine",
      "diamond.paint.creasepattern.CreasePattern$CreasePatternIterator",
      "diamond.viewsetting.main.uipanel.ChangeOnSelectButtonSelected",
      "diamond.paint.bisector.AngleBisectorAction",
      "diamond.paint.bisector.SelectingVertexForBisector",
      "diamond.viewsetting.main.uipanel.ChangeOnByValueButtonSelected",
      "diamond.paint.byvalue.LineByValueAction",
      "diamond.paint.byvalue.SelectingVertexToDrawLine",
      "diamond.paint.mirror.MirrorCopyAction",
      "diamond.paint.mirror.SelectingLineForMirror",
      "diamond.paint.line.TwoPointLineAction",
      "diamond.paint.line.SelectingFirstVertexForLine",
      "diamond.paint.pbisec.TwoPointBisectorAction",
      "diamond.paint.pbisec.SelectingFirstVertexForBisector",
      "diamond.paint.symmetric.SymmetricalLineAction",
      "diamond.paint.symmetric.SelectingVertexForSymmetric",
      "diamond.paint.triangle.TriangleSplitAction",
      "diamond.paint.triangle.SelectingVertexForTriangleSplit",
      "diamond.paint.vertical.VerticalLineAction",
      "diamond.paint.vertical.SelectingVertexForVertical",
      "diamond.file.ImageResourceLoader",
      "diamond.viewsetting.main.uipanel.FromLineTypeItemListener",
      "diamond.viewsetting.main.uipanel.ToLineTypeItemListener",
      "diamond.paint.byvalue.LengthMeasuringAction",
      "diamond.paint.byvalue.SelectingVertexForLength",
      "diamond.paint.byvalue.AngleMeasuringAction",
      "diamond.paint.byvalue.SelectingVertexForAngle",
      "diamond.paint.util.LineTypeSetter",
      "diamond.appstate.InputCommandStatePopper",
      "diamond.paint.byvalue.AbstractValueInputListener",
      "diamond.paint.byvalue.LengthValueInputListener",
      "diamond.paint.byvalue.AngleValueInputListener",
      "diamond.appstate.StateManager",
      "diamond.paint.creasepattern.Painter",
      "diamond.paint.creasepattern.tool.LineSelectionModifier",
      "diamond.view.estimation.EstimationResultFrame",
      "diamond.mouse.MouseUtility",
      "diamond.paint.geometry.GeometricOperation",
      "diamond.paint.geometry.NearestVertexFinder",
      "diamond.paint.geometry.NearestPoint",
      "diamond.geom.GeomUtil",
      "diamond.view.model.ModelViewFrame"
    );
  }
}
