/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Dec 04 17:11:42 GMT 2018
 */

package diamond.doc;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Doc_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "diamond.doc.Doc"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "MS932"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\long_\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "JP"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\long_\\git\\DIAMOND"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\long_"); 
    java.lang.System.setProperty("user.language", "ja"); 
    java.lang.System.setProperty("user.name", "long_"); 
    java.lang.System.setProperty("user.timezone", ""); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Doc_ESTest_scaffolding.class.getClassLoader() ,
      "diamond.resource.ResourceHolder",
      "diamond.paint.segment.SelectingSecondVertexForSegment",
      "diamond.resource.Constants$EditMode",
      "diamond.doc.Doc",
      "diamond.resource.ResourceKey",
      "diamond.paint.creasepattern.VerticesManager$AreaPosition",
      "diamond.paint.segment.TwoPointSegmentAction",
      "diamond.paint.segment.SelectingFirstVertexForSegment",
      "diamond.paint.creasepattern.VerticesManager",
      "diamond.Version",
      "diamond.fold.OriEdge",
      "diamond.fold.FoldedModelInfo",
      "diamond.doc.DocHolder",
      "diamond.paint.core.PaintConfig",
      "diamond.doc.UndoInfo",
      "diamond.resource.Constants",
      "diamond.resource.Constants$LineInputMode",
      "diamond.geom.Line",
      "diamond.resource.ExplanationStringResource_en",
      "diamond.value.OriLine",
      "diamond.paint.core.GraphicMouseAction",
      "diamond.paint.creasepattern.LineManager",
      "diamond.geom.Ray",
      "diamond.doc.UndoManager",
      "diamond.fold.OriFace",
      "diamond.paint.creasepattern.tool.LineAdder$PointComparatorY",
      "diamond.paint.creasepattern.tool.LineAdder$PointComparatorX",
      "diamond.fold.TriangleFace",
      "diamond.geom.GeomUtil",
      "diamond.paint.core.ActionState",
      "diamond.paint.core.AbstractActionState",
      "diamond.value.OriPoint",
      "diamond.resource.WarningStringResource_en",
      "diamond.paint.ScreenUpdaterInterface",
      "diamond.fold.OriVertex",
      "diamond.paint.creasepattern.tool.LineAdder",
      "diamond.paint.core.PickingVertex",
      "diamond.paint.creasepattern.CreasePattern",
      "diamond.geom.Segment",
      "diamond.fold.OriHalfedge",
      "diamond.fold.OrigamiModel",
      "diamond.paint.creasepattern.CreasePattern$CreasePatternIterator",
      "diamond.value.OriLine$Type",
      "diamond.resource.LabelStringResource_en",
      "diamond.paint.GraphicMouseActionInterface",
      "diamond.paint.EditMode",
      "diamond.fold.BoundBox",
      "diamond.resource.Constants$ModelDispMode",
      "diamond.paint.core.PaintContext"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Doc_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "diamond.doc.Doc",
      "diamond.doc.UndoManager",
      "diamond.paint.creasepattern.CreasePattern",
      "diamond.paint.creasepattern.LineManager",
      "diamond.paint.creasepattern.VerticesManager",
      "diamond.value.OriLine",
      "diamond.value.OriLine$Type",
      "diamond.value.OriPoint",
      "diamond.paint.creasepattern.VerticesManager$AreaPosition",
      "diamond.fold.OrigamiModel",
      "diamond.fold.FoldedModelInfo",
      "diamond.fold.BoundBox",
      "diamond.doc.DocHolder",
      "diamond.resource.ResourceKey",
      "diamond.resource.ExplanationStringResource_en",
      "diamond.Version",
      "diamond.resource.LabelStringResource_en",
      "diamond.resource.WarningStringResource_en",
      "diamond.resource.ResourceHolder",
      "diamond.resource.Constants$ModelDispMode",
      "diamond.paint.core.GraphicMouseAction",
      "diamond.paint.segment.TwoPointSegmentAction",
      "diamond.paint.EditMode",
      "diamond.paint.core.AbstractActionState",
      "diamond.paint.core.PickingVertex",
      "diamond.paint.segment.SelectingFirstVertexForSegment",
      "diamond.paint.core.PaintConfig",
      "diamond.doc.UndoInfo",
      "diamond.paint.creasepattern.CreasePattern$CreasePatternIterator",
      "diamond.geom.Line",
      "diamond.geom.Segment",
      "diamond.paint.creasepattern.tool.LineAdder",
      "diamond.geom.GeomUtil",
      "diamond.paint.creasepattern.tool.LineAdder$PointComparatorY",
      "diamond.fold.OriVertex",
      "diamond.fold.OriFace",
      "diamond.fold.OriHalfedge",
      "diamond.fold.OriEdge",
      "diamond.paint.creasepattern.tool.LineAdder$PointComparatorX",
      "diamond.fold.TriangleFace"
    );
  }
}
