/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Dec 04 16:50:55 GMT 2018
 */

package diamond.view.model;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ModelViewFrame_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "diamond.view.model.ModelViewFrame"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "MS932"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\long_\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "JP"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\long_\\git\\DIAMOND"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\long_"); 
    java.lang.System.setProperty("user.language", "ja"); 
    java.lang.System.setProperty("user.name", "long_"); 
    java.lang.System.setProperty("user.timezone", ""); 
    java.lang.System.setProperty("sun.java.launcher", "SUN_STANDARD"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ModelViewFrame_ESTest_scaffolding.class.getClassLoader() ,
      "diamond.resource.ResourceHolder",
      "diamond.paint.segment.SelectingSecondVertexForSegment",
      "diamond.viewsetting.main.uipanel.UIPanelSettingDB",
      "diamond.doc.exporter.ExporterDXF",
      "diamond.file.FileVersionError",
      "diamond.resource.Constants$EditMode",
      "diamond.view.main.menubar.edit.UnselectAll",
      "diamond.doc.Doc",
      "diamond.view.main.HintLabel",
      "diamond.resource.ResourceKey",
      "diamond.paint.creasepattern.VerticesManager$AreaPosition",
      "diamond.paint.segment.TwoPointSegmentAction",
      "diamond.paint.segment.SelectingFirstVertexForSegment",
      "diamond.view.main.menubar.MenuFile",
      "diamond.Version",
      "diamond.paint.creasepattern.VerticesManager",
      "diamond.fold.FoldedModelInfo",
      "diamond.view.main.menubar.file.Save",
      "diamond.viewsetting.ViewSettingDataBase",
      "diamond.doc.DocHolder",
      "diamond.paint.core.PaintConfig",
      "diamond.view.model.ModelViewScreen",
      "diamond.doc.UndoInfo",
      "diamond.resource.Constants",
      "diamond.resource.Constants$LineInputMode",
      "diamond.viewsetting.main.MainScreenSettingDB",
      "diamond.view.main.menubar.file.Exit",
      "diamond.geom.Line",
      "diamond.view.main.menubar.MenuEdit",
      "diamond.paint.creasepattern.tool.TypeForChange",
      "diamond.doc.loader.LoaderCP",
      "diamond.resource.ExplanationStringResource_en",
      "diamond.file.FileFilterEx",
      "diamond.file.SavingAction",
      "diamond.value.OriLine",
      "diamond.paint.core.GraphicMouseAction",
      "diamond.doc.LoadingDoc",
      "diamond.doc.exporter.ExporterOBJ",
      "diamond.paint.creasepattern.LineManager",
      "diamond.doc.exporter.ExporterSVG",
      "diamond.doc.UndoManager",
      "diamond.doc.loader.LoaderXML",
      "diamond.viewsetting.ChangeViewSetting",
      "diamond.view.main.UIPanel",
      "diamond.view.main.PainterScreen",
      "diamond.paint.core.ActionState",
      "diamond.paint.core.AbstractActionState",
      "diamond.viewsetting.model.ModelFrameSettingDB",
      "diamond.view.main.menubar.file.New",
      "diamond.value.OriPoint",
      "diamond.resource.WarningStringResource_en",
      "diamond.view.main.menubar.file.Open",
      "diamond.paint.ScreenUpdaterInterface",
      "diamond.paint.core.PickingVertex",
      "diamond.file.FilterDB",
      "diamond.doc.exporter.ExporterXML",
      "diamond.paint.creasepattern.CreasePattern",
      "diamond.geom.Segment",
      "diamond.viewsetting.ViewScreenUpdater",
      "diamond.bind.binder.BinderInterface",
      "diamond.fold.OrigamiModel",
      "diamond.view.main.menubar.edit.RepeatCopy",
      "diamond.resource.LabelStringResource_en",
      "diamond.value.OriLine$Type",
      "diamond.file.LoadingAction",
      "diamond.viewsetting.main.ScreenUpdater",
      "diamond.view.main.MainFrame",
      "diamond.view.main.menubar.file.Property",
      "diamond.doc.loader.LoaderPDF",
      "diamond.paint.GraphicMouseActionInterface",
      "diamond.paint.EditMode",
      "diamond.view.main.menubar.help.About",
      "diamond.bind.ButtonFactory",
      "diamond.view.main.menubar.edit.CircleCopy",
      "diamond.fold.BoundBox",
      "diamond.view.main.menubar.MenuHelp",
      "diamond.view.main.menubar.file.SaveAs",
      "diamond.doc.exporter.ExporterCP",
      "diamond.doc.loader.Loader",
      "diamond.resource.Constants$ModelDispMode",
      "diamond.view.model.ModelViewFrame",
      "diamond.paint.core.PaintContext",
      "diamond.doc.exporter.Exporter",
      "diamond.doc.SavingDoc",
      "diamond.view.main.menubar.edit.Undo",
      "diamond.doc.exporter.ExporterPNG",
      "diamond.view.main.menubar.MenuBar",
      "diamond.doc.loader.LoaderDXF"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ModelViewFrame_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "diamond.view.model.ModelViewFrame",
      "diamond.resource.ResourceKey",
      "diamond.resource.ExplanationStringResource_en",
      "diamond.Version",
      "diamond.resource.LabelStringResource_en",
      "diamond.resource.WarningStringResource_en",
      "diamond.resource.ResourceHolder",
      "diamond.viewsetting.ViewSettingDataBase",
      "diamond.viewsetting.model.ModelFrameSettingDB",
      "diamond.doc.Doc",
      "diamond.doc.UndoManager",
      "diamond.paint.creasepattern.CreasePattern",
      "diamond.paint.creasepattern.LineManager",
      "diamond.paint.creasepattern.VerticesManager",
      "diamond.value.OriLine",
      "diamond.value.OriLine$Type",
      "diamond.value.OriPoint",
      "diamond.paint.creasepattern.VerticesManager$AreaPosition",
      "diamond.fold.OrigamiModel",
      "diamond.fold.FoldedModelInfo",
      "diamond.fold.BoundBox",
      "diamond.doc.DocHolder",
      "diamond.view.main.MainFrame",
      "diamond.resource.Constants$ModelDispMode",
      "diamond.paint.core.GraphicMouseAction",
      "diamond.paint.segment.TwoPointSegmentAction",
      "diamond.paint.EditMode",
      "diamond.paint.core.AbstractActionState",
      "diamond.paint.core.PickingVertex",
      "diamond.paint.segment.SelectingFirstVertexForSegment",
      "diamond.paint.core.PaintConfig",
      "diamond.view.main.PainterScreen",
      "diamond.paint.core.PaintContext",
      "diamond.viewsetting.main.ScreenUpdater",
      "diamond.viewsetting.main.MainScreenSettingDB"
    );
  }
}
