/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 16:43:57 GMT 2018
 */

package diamond.doc.loader;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import diamond.doc.Doc;
import diamond.doc.loader.LoaderDXF;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LoaderDXF_ESTest extends LoaderDXF_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "11");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "11");
      Doc doc0 = loaderDXF0.load("skip");
      assertNull(doc0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "20");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "20");
      Doc doc0 = loaderDXF0.load("skip");
      assertNull(doc0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "10");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "10");
      Doc doc0 = loaderDXF0.load("skip");
      assertNull(doc0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      loaderDXF0.load("skip");
      loaderDXF0.load("20");
      loaderDXF0.load("20");
      loaderDXF0.load("~");
      loaderDXF0.load("10");
      loaderDXF0.load("########### NULL EDGE");
      loaderDXF0.load("skip");
      loaderDXF0.load("H!lEWSp,r:=~*qb");
      loaderDXF0.load("");
      // Undeclared exception!
      loaderDXF0.load("");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "21");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "0");
      Doc doc0 = loaderDXF0.load("skip");
      assertNull(doc0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "21");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "21");
      Doc doc0 = loaderDXF0.load("skip");
      assertNull(doc0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "21");
      // Undeclared exception!
      try { 
        loaderDXF0.load("skip");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "2/20");
      // Undeclared exception!
      try { 
        loaderDXF0.load("skip");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "62");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "62");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "62");
      Doc doc0 = loaderDXF0.load("skip");
      assertNull(doc0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "62");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "62");
      Doc doc0 = loaderDXF0.load("skip");
      assertNull(doc0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      byte[] byteArray0 = new byte[2];
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      Doc doc0 = loaderDXF0.load("skip");
      assertNull(doc0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LoaderDXF loaderDXF0 = new LoaderDXF();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("skip");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "LINE");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "0#62");
      Doc doc0 = loaderDXF0.load("skip");
      assertNull(doc0.getTitle());
  }
}
