/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 16:17:36 GMT 2018
 */

package diamond.view.estimation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import diamond.view.estimation.FoldedModelScreen;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FoldedModelScreen_ESTest extends FoldedModelScreen_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FoldedModelScreen.clear();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FoldedModelScreen foldedModelScreen0 = new FoldedModelScreen();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FoldedModelScreen.setM_bFaceOrderFlip(true);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      boolean boolean0 = FoldedModelScreen.isM_bFaceOrderFlip();
      assertFalse(boolean0);
  }
}
